[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc="0.8.25"

[rpc_endpoints]
sepolia = "${ETH_PRC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
