[profile.default]
src = "src"
out = "out"
libs = ["lib"]


solc="0.8.25"

[fmt]
line_length = 120
tab_width = 2
bracket_spacing = true
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
