[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc="0.8.25"

ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]

[rpc_endpoints]
sepolia = "wss://ethereum-sepolia-rpc.publicnode.com"


